package gather.database.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import gather.database.bean.OrgActMsg;
import gather.database.bean.SystemMsg;

import gather.database.dao.OrgActMsgDao;
import gather.database.dao.SystemMsgDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig orgActMsgDaoConfig;
    private final DaoConfig systemMsgDaoConfig;

    private final OrgActMsgDao orgActMsgDao;
    private final SystemMsgDao systemMsgDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        orgActMsgDaoConfig = daoConfigMap.get(OrgActMsgDao.class).clone();
        orgActMsgDaoConfig.initIdentityScope(type);

        systemMsgDaoConfig = daoConfigMap.get(SystemMsgDao.class).clone();
        systemMsgDaoConfig.initIdentityScope(type);

        orgActMsgDao = new OrgActMsgDao(orgActMsgDaoConfig, this);
        systemMsgDao = new SystemMsgDao(systemMsgDaoConfig, this);

        registerDao(OrgActMsg.class, orgActMsgDao);
        registerDao(SystemMsg.class, systemMsgDao);
    }
    
    public void clear() {
        orgActMsgDaoConfig.getIdentityScope().clear();
        systemMsgDaoConfig.getIdentityScope().clear();
    }

    public OrgActMsgDao getOrgActMsgDao() {
        return orgActMsgDao;
    }

    public SystemMsgDao getSystemMsgDao() {
        return systemMsgDao;
    }

}
